### ISSUE TITLE
2.2.3: no version message at daemon start

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#34] opened 2021-05-15 09:29 UTC
2.2.2 sysklogd writes a version string to the log file like the following:

`May 15 11:18:42 jue syslogd[32090]: syslogd v2.2.2: restart.`

Is it intentional that 2.2.3 dosn't print the version information at daemon start?

**Comment by troglobit** [comment] 2021-05-15 13:44
Um no, that's a regression.

**Comment by troglobit** [comment] 2021-05-16 15:05
I just tried to reproduce this, not only do I get that message at start, I also get it at restart.  So cannot reproduce your problem. Could you tell me a bit more about your environment?  Otherwise I'll have to close this.

```
root@buildroot:~# date; head -1 /var/log/syslog; killall -HUP syslogd; tail -1 /var/log/syslog
Sun May 16 15:04:02 UTC 2021
May 16 08:42:55 buildroot syslogd[1050]: syslogd v2.2.3: restart.
May 16 15:04:02 buildroot syslogd[1050]: syslogd v2.2.3: restart.
```

Here I'm running latest buildroot LTS, glibc.

**Comment by fjaell** [comment] 2021-05-16 16:27
Restarting syslog by sending HUP works for me too, but if I send TERM to syslogd and start it afterwards I get not message at all.

**Comment by troglobit** [comment] 2021-05-16 17:03
Term and start works for me too.  Could you tell me a bit more about your environment?

**Comment by fjaell** [comment] 2021-05-16 17:10
Here's what I did to reproduce the issue:

`# killall syslogd`
`# pgrep syslogd`
`# syslogd` 
`# tail -1 /var/log/messages` 
`May 16 18:55:12 jue syslogd[8345]: exiting on signal 15`

up-to-date CRUX system with glibc 2.32, kernel 5.11.19

**Comment by troglobit** [comment] 2021-05-16 21:45
Truly weird, I cannot for the life of me reproduce this!  Sorry, but I'll have to leave this open until I circle back to sysklogd again next time.  Unless someone beats me to tracking this one down.

**Comment by opty77** [comment] 2021-06-20 12:40
No sysklogd's messages at all except `-- MARK --` here.

**Comment by troglobit** [comment] 2021-06-20 12:49
OK, I'm back working on sysklogd again, so I'll look into this now along with a few other issues.

@opty77 do you really not get any messages as all after (re)start?

**Comment by opty77** [comment] 2021-06-20 13:07
No sysklogd's **own** messages except `-- MARK --`. I'm using `;RFC5424` if that matters.

**Comment by troglobit** [comment] 2021-06-20 13:15
OK, thanks, that helps!

**Comment by opty77** [comment] 2021-06-23 13:52
<code>/bin/kill -HUP \`cat /var/run/syslogd.pid 2>/dev/null\`</code> in a script works but not in _/etc/logrotate.d/syslog_. o_O

**Comment by troglobit** [comment] 2021-06-23 15:29
Wut? That's just nuts

**Comment by opty77** [comment] 2021-06-24 15:31
Welcome to my life. :-)

Distribution's _/etc/logrotate.d/syslog_ contains exactly <code>/bin/kill -HUP \`cat /var/run/syslogd.pid 2>/dev/null\` 2>/dev/null || true</code> which I changed to `/home/opty/bin/hup-syslogd 2>/dev/null || true` yesterday (the script itself works).

We'll probably see on Sunday when logrotate runs again.

**Comment by opty77** [comment] 2021-06-28 11:41
No change. :-/

**Comment by troglobit** [comment] 2021-06-28 15:59
OK, that's both good and bad. I like that the problem is consistent.

Just to verify, @fjaell runs Slackware-current and @opty77 runs CRUX, or have I mixed you up?  I've spent a few days last week, and the one before that, to get a CRUX and Slacware-current setup up and running. Unfortunately I only managed Slackware, couldn't wrap my head around CRUX.  As soon as I get the rest of my lab network set up, I'll get back to this.  Other related $DAYJOB issues have helped raise the priority of sysklogd again :)

**Comment by opty77** [comment] 2021-06-29 10:25
I was thinking the same thing and yes, you mixed us up, Slackware -current here. :-)

**Comment by troglobit** [comment] 2021-06-30 20:03
OK, I've reproduced this on Slackware current now.  Still trying to figure out what's going on ...

**Comment by troglobit** [comment] 2021-06-30 20:29
OK, found it.  Can confirm this really was a regression introduced between v2.2.2 and v2.2.3.

**Closed** 2021-06-30 20:28 UTC
Labels: question

**Comment by fjaell** [comment] 2021-07-05 13:54
confirmed, works again. Thanks :)
