### ISSUE TITLE
O_CLOEXEC not available on all systems

### ISSUE THREAD

**Issue by gnijieb** [troglobit/sysklogd#24] opened 2020-12-08 20:33 UTC
I was updating sysklogd in buildroot.

buildroot maintainer Thomas Petazzoni sent me a notice that sysklogd 2.1.2 will not build under some circumstances, because some build environments are lacking the definition of O_CLOEXEC (see http://lists.busybox.net/pipermail/buildroot/2020-December/297937.html).

This could be solved by either defining O_CLOEXEC if not defined or using close_on_exec_on.
Another way could be defining _GNU_SOURCE in CFLAGS or in code before including fcntl.h.
I just now saw you already defined _GNU_SOURCE in lib/pidfile.c, so maybe extend this so it is used in src/syslog.c. src/syslogd.c too.

To reproduce the issue with buildroot:
Get buildroot
Apply patch from http://lists.busybox.net/pipermail/buildroot/2020-August/289056.html
Use the defconfig mentioned by Thomas

**Comment by troglobit** [comment] 2020-12-09 03:54
Hi, this is great!

Been meaning to do this myself in Buildroot, but haven't gotten around to it yet.  Was saving it for the upcoming holidays.  We actually use if for our work project already :+1: 

  https://github.com/westermo/netbox/tree/master/package/sysklogd2

I did some initial work myself, started testing with the Buildroot test toolchains etc. Ran into the same problem as you, and fixed it on the main branch, see https://github.com/troglobit/sysklogd/commit/93117e58016de6f604e67263b5135adbba032367 for details.

There is a new release planned, which would include this patch, but for now you'll have to backport it.

Surprised you didn't get any more feedback on the removal of `klogd` from Thomas.  Good he mentioned the license change, it was one of towo huge deals in sysklogd v2.  The *main* point, however, was the new `syslogp()` API in the accompanying `libsyslog` to enable RFC5424 style log messages from applications, e.g. MsgID.  The native `logger` tool is the only way to send such messages if not using `libsyslog` ... is there any way you could make `logger` optional with menuconfig or something?

**Comment by troglobit** [comment] 2020-12-18 08:24
@gnijieb how is it progressing, I hope my reply helped you?  If not, please let me know how I can help you out.

**Comment by gnijieb** [comment] 2020-12-21 09:50
@troglobit Sorry, it has been pretty busy the last weeks. If I don't find time this week I will work on it in between years.

I will add you to the discussion on the buildroot list if that's okay.

**Comment by troglobit** [comment] 2020-12-21 10:19
@gnijieb No problem, just worried you didn't get the notification of my reply.  Yes, please do include me, very appreciated! :-)

**Comment by troglobit** [comment] 2021-01-14 17:22
So, releasing a v2.2.0 later today, or tomorrow at the latest.  Managed to get some time this week to do regression testing.  Therefore I'm closing this bug report since it's fixed in 93117e5. I'll get right to giving feedback on the Buildroot mailing list.

**Closed by troglobit** 2021-01-14 17:22 UTC
